name: deploy-angular-to-hostinger-ftp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build (Angular)
        run: npm run build
        # If your site is under a sub-path like /app/, use:
        # run: npx ng build --base-href /app/

      - name: Ensure .htaccess (SPA routing)
        run: |
          cat > dist/myportfolio/.htaccess << 'EOF'
          Options -MultiViews
          RewriteEngine On
          RewriteBase /
          RewriteCond %{REQUEST_FILENAME} -f [OR]
          RewriteCond %{REQUEST_FILENAME} -d
          RewriteRule ^ - [L]
          RewriteRule . /index.html [L]
          EOF

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          protocol: ftp                 # change to ftp or ftps-legacy if needed
          server:   ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          local-dir:  dist/myportfolio/  # <-- hardcoded build output
          server-dir: /public_html/      # <-- hardcoded Hostinger document root
          dangerous-clean-slate: true
          exclude: |
            **/*.map
            **/node_modules/**
            **/.git**
            **/.DS_Store
