name: build-and-deploy-angular-to-hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: hostinger-deploy
  cancel-in-progress: true

# If your Angular app is in a subfolder, uncomment and set it:
# defaults:
#   run:
#     working-directory: myportfolio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: Resolve dist folder
        id: dist
        run: |
          BUILD_DIR="$(ls -d dist/*/ 2>/dev/null | head -n 1)"
          BUILD_DIR="${BUILD_DIR%/}"
          [ -z "$BUILD_DIR" ] && BUILD_DIR="dist"
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
          echo "Resolved: $BUILD_DIR"

      - name: Add .htaccess (SPA)
        run: |
          cat > "${{ env.BUILD_DIR }}/.htaccess" << 'EOF'
          Options -MultiViews
          RewriteEngine On
          RewriteBase /
          RewriteCond %{REQUEST_FILENAME} -f [OR]
          RewriteCond %{REQUEST_FILENAME} -d
          RewriteRule ^ - [L]
          RewriteRule . /index.html [L]
          EOF

      - name: Publish dist to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: ${{ env.BUILD_DIR }}
          clean: true

      - name: Trigger Hostinger auto-deploy webhook
        run: |
          curl -fsS -X POST "$HOSTINGER_WEBHOOK_URL" || curl -fsS "$HOSTINGER_WEBHOOK_URL" || true
        env:
          HOSTINGER_WEBHOOK_URL: ${{ secrets.HOSTINGER_WEBHOOK_URL }}
