name: build-and-deploy-angular-to-hostinger

on:
  push:
    branches: [ main ]      # change if your primary branch is different
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: hostinger-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        run: npm run build

      - name: Resolve dist folder
        run: |
          BUILD_DIR="$(ls -d dist/*/ 2>/dev/null | head -n 1)"
          BUILD_DIR="${BUILD_DIR%/}"
          if [ -z "$BUILD_DIR" ]; then BUILD_DIR="dist"; fi
          echo "BUILD_DIR=$BUILD_DIR" >> "$GITHUB_ENV"

      - name: Add .htaccess (SPA)
        run: |
          cat > "${{ env.BUILD_DIR }}/.htaccess" << 'EOF'
          Options -MultiViews
          RewriteEngine On
          RewriteBase /

          RewriteCond %{REQUEST_FILENAME} -f [OR]
          RewriteCond %{REQUEST_FILENAME} -d
          RewriteRule ^ - [L]

          RewriteRule . /index.html [L]
          EOF

      - name: Publish dist/ to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: ${{ env.BUILD_DIR }}
          clean: true

      # 🔔 Explicitly ping Hostinger to pull the 'deploy' branch into /public_html
      - name: Trigger Hostinger auto-deploy webhook
        run: |
          # Try POST first; fall back to GET if POST is not accepted
          curl -fsS -X POST "$HOSTINGER_WEBHOOK_URL" || curl -fsS "$HOSTINGER_WEBHOOK_URL" || true
        env:
          HOSTINGER_WEBHOOK_URL: ${{ secrets.HOSTINGER_WEBHOOK_URL }}
