name: build-and-deploy-angular-to-hostinger

on:
  push:
    branches: [ main ]     # change if you use a different default branch
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: hostinger-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node with cache only if an npm lock file exists
      - name: Setup Node (with npm cache)
        if: ${{ hashFiles('**/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Setup Node (no cache)
        if: ${{ hashFiles('**/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install deps: prefer reproducible 'ci' if lock exists, else fallback to 'install'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "No package-lock.json found; using 'npm install'. Consider committing a lock file for reproducible builds."
            npm install
          fi

      # Build Angular (uses production by default if your angular.json defaultConfiguration=production)
      - name: Build
        run: npm run build

      # Resolve the dist folder (e.g., dist/myportfolio). Change this if you know it exactly.
      - name: Resolve dist folder
        id: dist
        run: |
          BUILD_DIR="$(ls -d dist/*/ 2>/dev/null | head -n 1)"
          BUILD_DIR="${BUILD_DIR%/}"
          if [ -z "$BUILD_DIR" ]; then
            echo "No dist subfolder found; using dist"
            BUILD_DIR="dist"
          fi
          echo "BUILD_DIR=$BUILD_DIR" >> "$GITHUB_ENV"
          echo "folder=$BUILD_DIR" >> "$GITHUB_OUTPUT"

      # Add SPA rewrite so deep links work on Hostinger/Apache
      - name: Add .htaccess SPA rewrite
        run: |
          cat > "${{ env.BUILD_DIR }}/.htaccess" << 'EOF'
          Options -MultiViews
          RewriteEngine On
          RewriteBase /

          RewriteCond %{REQUEST_FILENAME} -f [OR]
          RewriteCond %{REQUEST_FILENAME} -d
          RewriteRule ^ - [L]

          RewriteRule . /index.html [L]
          EOF

      # Push only built files to 'deploy' branch (Hostinger auto-pulls that branch to /public_html)
      - name: Publish to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: ${{ env.BUILD_DIR }}
          clean: true
